#!/usr/bin/env bash
# Set up a RunPod GPU pod to serve the regrag LLM with vLLM. Idempotent: safe to
# re-run; finished steps are skipped. Everything lives on /workspace (attach a
# network volume there), so a fresh pod on any machine reuses env + weights.
#
#   bash /workspace/setup.sh            # then: tmux new -s vllm; /workspace/serve.sh
#
# Overridable: MODEL, VLLM_VERSION, MAX_MODEL_LEN, MAX_NUM_SEQS
set -euo pipefail

WS=/workspace
MODEL=${MODEL:-Qwen/Qwen3.8-27B-FP8}
VLLM_VERSION=${VLLM_VERSION:-0.31.0}
MAX_MODEL_LEN=${MAX_MODEL_LEN:-32768}
MAX_NUM_SEQS=${MAX_NUM_SEQS:-64}
ENV=$WS/vllm-env
export HF_HOME=$WS/hf

step() { echo; echo "=== $*"; }

step "1/6 GPU and driver"
nvidia-smi --query-gpu=name,memory.total,driver_version --format=csv,noheader
# The driver caps the CUDA runtime we may install (e.g. "CUDA Version: 12.8").
CUDA_MAJOR=$(nvidia-smi | sed -n 's/.*CUDA Version: *\([0-9]*\)\..*/\1/p')
echo "driver supports CUDA ${CUDA_MAJOR}.x"
df -h $WS | tail -1

step "2/6 uv"
if [ ! -x "$HOME/.local/bin/uv" ]; then
  curl -LsSf https://astral.sh/uv/install.sh | sh
fi
UV="$HOME/.local/bin/uv"   # full path: the template may ship an older uv first in PATH

step "3/6 vLLM $VLLM_VERSION environment"
if [ ! -x "$ENV/bin/vllm" ]; then
  "$UV" venv "$ENV" --python 3.12
  if [ "$CUDA_MAJOR" -ge 13 ]; then
    # Default PyPI build targets CUDA 13: needs a 580+ driver.
    "$UV" pip install --python "$ENV/bin/python" "vllm==$VLLM_VERSION"
  else
    # CUDA 12.x driver: vLLM's cu129 build + PyTorch from the cu129 index
    # (minor-version compatibility: any 12.x runtime runs on any 12.x driver).
    "$UV" pip install --python "$ENV/bin/python" \
      "https://github.com/vllm-project/vllm/releases/download/v${VLLM_VERSION}/vllm-${VLLM_VERSION}+cu129-cp38-abi3-manylinux_2_28_x86_64.whl" \
      --torch-backend=cu129
  fi
else
  echo "already installed: $("$ENV/bin/python" -c 'import vllm; print(vllm.__version__)')"
fi

step "4/6 GPU smoke test (real work, not just is_available())"
"$ENV/bin/python" - <<'EOF'
import torch
a = torch.randn(4096, 4096, device="cuda", dtype=torch.bfloat16)
assert (a @ a).float().abs().mean().item() > 0
x = torch.randn(64, 64, device="cuda").to(torch.float8_e4m3fn)
print("ok:", torch.__version__, torch.cuda.get_device_name(0), "capability", torch.cuda.get_device_capability())
EOF

step "5/6 model weights ($MODEL)"
"$ENV/bin/hf" download "$MODEL"
du -sh "$HF_HOME"

step "6/6 API key, serve.sh, tmux"
if [ ! -s "$WS/.vllm_key" ]; then
  openssl rand -hex 24 > "$WS/.vllm_key"
fi
cat > "$WS/serve.sh" <<EOF
#!/bin/bash
# Generated by setup.sh. Binds to 127.0.0.1 only: reach it through an SSH tunnel.
source $ENV/bin/activate
export HF_HOME=$HF_HOME
export VLLM_API_KEY=\$(cat $WS/.vllm_key)
exec vllm serve $MODEL \\
  --host 127.0.0.1 --port 8000 \\
  --max-model-len $MAX_MODEL_LEN \\
  --max-num-seqs $MAX_NUM_SEQS \\
  --kv-cache-dtype fp8 \\
  --language-model-only \\
  --reasoning-parser qwen3 \\
  --gpu-memory-utilization 0.92 \\
  --enable-prefix-caching
EOF
chmod +x "$WS/serve.sh"
command -v tmux >/dev/null || (apt-get update -qq && apt-get install -y -qq tmux)

echo
echo "Done. API key (put it in your laptop's .env as VLLM_API_KEY):"
cat "$WS/.vllm_key"
echo
echo "Start the server:  tmux new -s vllm   then   $WS/serve.sh 2>&1 | tee $WS/vllm.log"
